### ISSUE TITLE
 @

### ISSUE THREAD

**Issue by ChorlyVan** [zhangbaijin/Constractive-learning-shadow-removal#2]

**Comment by zhangbaijin** [comment]
Have you solved the problem？ The code is MPRNet(derainging), you can copy the code on your GPU, and download my pretrained model to test it.

**Comment by ChorlyVan** [comment]
您好，我是初学者，之前没有明白项目运行方法，目前明白了，但是我在实际运行中出现了如下报错，请问是因为我的cuda版本不一致而导致的吗？
python demo.py --task CloudRemoval  --input_dir ./input --result_dir ./out
Traceback (most recent call last):
  File "/home/chorlee/PycharmProjects/MPRNet-main/demo.py", line 74, in <module>
    restored = model(input_)
  File "/home/chorlee/.conda/envs/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "CloudRemoval/MPRNet.py", line 294, in forward
    feat1_ltop = self.stage1_encoder(x1ltop)
  File "/home/chorlee/.conda/envs/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "CloudRemoval/MPRNet.py", line 119, in forward
    enc3= self.mem_rep(enc3)
  File "/home/chorlee/.conda/envs/env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Encoder' object has no attribute 'mem_rep'

**Comment by zhangbaijin** [comment]
不是的，你可以在MPRNet里面删掉memory module，当时我想改的不过没有改通，或者你把MPRNet改成我的代码里面的

**Comment by ChorlyVan** [comment]
好的，感谢您能于百忙之中抽空解答，我使用您的MPRNet依然是同样的报错，我认为可能是环境不一致导致，我严格按照您的readme文件中所描述版本要求重新配置conda环境试试

**Comment by zhangbaijin** [comment]
你可以先MPRNet，然后把我的预训练模型放进去测试就行了，我的是去云模型

**Comment by ChorlyVan** [comment]
您好，经过检查，我找出了我这边报错的原因所在，MPRNet.py中第122行，enc3= self.mem_rep(enc3)此处的mem_rep函数未经定义，所以运行到此处时会有一次报错，另外去云模型model_best效果似乎有点过好，某些地面信息也被去除了，请问可以告知一下您在去云工作中所使用的数据集吗？

**Comment by zhangbaijin** [comment]
我重新更新了github，数据集用的是RICE dataset，还有个去阴影的数据集是ISTD

**Comment by ChorlyVan** [comment]
感谢，我现在本科毕业设计课题方向正是遥感去云，感谢您的不吝赐教，在google scholar看到您在遥感去云方向有所研究，希望我也能做出成果并在后续的毕业论文中能够引用您在此方向的论文

**Comment by zhangbaijin** [comment]
加油，MPRNet遥感图像去云可以尝试的，不能说效果多好，但是马马虎虎吧，做个毕设没什么问题
