### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by Z-YHDD** [zhangbaijin/Constractive-learning-shadow-removal#8]
运行后报错，找不到文件
PS C:\Users\dell\Desktop\yhdd\test_cloud\MemoryNet-main> python demo.py --task Deraining --input_dir ./Test-image-RICE/cloudy_image --result_dir ./result/1.png
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\yhdd\test_cloud\MemoryNet-main\demo.py", line 52, in <module>
    load_file = run_path(os.path.join(task, "MPRNet.py"))
  File "D:\yhdd\language\python\lib\runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "D:\yhdd\language\python\lib\runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dell\\Desktop\\yhdd\\test_cloud\\MemoryNet-main\\Deraining\\MPRNet.py'

**Comment by zhangbaijin** [comment]
已经进行更新，可以重新demo一下
